name: Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18
  NODE_CACHE: "yarn"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Create/Update release PR or publish to NPM
        uses: changesets/action@v1.4.5
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CI_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
